# Operations On Array:
Numpy support various operations on array such as addition, subtraction, multiplication, division, etc.

In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

# Addition
c = a + b
# Subtraction
d = a - b
# Multiplication
e = a * b
# Division
f = a / b
# Modulus
g = a % b

print("Addition:", c)
print("Subtraction:", d)
print("Multiplication:", e)
print("Division:", f)
print("Modulus:", g)


Addition: [ 7  9 11 13 15]
Subtraction: [-5 -5 -5 -5 -5]
Multiplication: [ 6 14 24 36 50]
Division: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Modulus: [1 2 3 4 5]


# What is Broadcasting?

**Broadcasting** in NumPy is a way to perform operations on arrays of different shapes and sizes without making extra copies of data.  
It “stretches” the smaller array across the larger one so their shapes match for element-wise operations.

### **Easy Example**

Suppose you have:

- A 2D array:  
  ```
  [[1, 2, 3],
   [4, 5, 6]]
  ```
- A 1D array:  
  ```
  [10, 20, 30]
  ```

If you add them:


In [4]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([10, 20, 30])
print(a + b)

[[11 22 33]
 [14 25 36]]


**Result:**


In [ ]:
[[11 22 33]
 [14 25 36]]

**How?**  
NumPy “stretches” `b` to match the shape of `a`:



In [ ]:
[[10, 20, 30],   ← b is repeated for each row
 [10, 20, 30]]



---

### **Broadcasting Visual**



In [ ]:
a: 2 x 3      b: 1 x 3
[[1 2 3]      [10 20 30]
 [4 5 6]]

Result:
[[1+10 2+20 3+30]
 [4+10 5+20 6+30]]

![Broadcasting Visual](broadcastingfigure.png)



---

### **Stretching**

**Stretching** is just a way of saying NumPy repeats the smaller array along the missing dimension(s) so the shapes match.

---

**Summary:**  
- Broadcasting lets you do math with arrays of different shapes.
- NumPy “stretches” the smaller array as needed.
- No extra memory is used for the stretched array.

---

**Tip:**  
Broadcasting only works when the shapes are compatible (from the end: dimensions are equal or one of them is 1).

# Rules of Broadcasting
1. The dimenssions of any of one array should be one (1).
2. Compare the shapes from the right to the left.

In [ ]:
# Broadcasting example
array1=np.array([1,2,3,4])
array2=np.array([10,20,30,40,50])
print(array1 + array2)
# This will raise an error because the shapes are not compatible for broadcasting one has 4 elements and the other has 5 elements or columns.

In [ ]:
# Another example of broadcasting
a = np.array([[1, 2, 3],
              [4, 5, 6]]) # 2x3 array
b=np.array([2,2,2]) # 1x3 array
# Broadcasting will repeat b for each row of a 
"""
Or In simple terms that the rule of broadcasting is that the dimensions of any of one array should be one (1)
and b is matching like 1x3 so 1 is matching with 2x3
"""
print(a + b)

[[3 4 5]
 [6 7 8]]


# Vectorization

**Vectorization** in NumPy means performing operations on entire arrays (vectors, matrices) at once, instead of using loops to process each element one by one.

**Simple explanation:**  
- You write code like `a + b` to add two arrays, and NumPy automatically adds each element for you, very fast.
- This is much quicker and easier than using a `for` loop.

**Example:**



In [7]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b  # Vectorized addition
print(c)   # Output: [5 7 9]

[5 7 9]




**Benefits:**  
- Code is shorter and easier to read.
- Runs much faster because NumPy uses optimized C code under the hood.