# Numpy Array Attributes:


NumPy arrays have several useful attributes that describe their structure and data:

- **ndim**: Number of dimensions (axes) of the array.
- **shape**: Tuple representing the size of each dimension.
- **size**: Total number of elements in the array.
- **dtype**: Data type of the array elements.
- **itemsize**: Size (in bytes) of each element.
- **nbytes**: Total bytes consumed by the array.
- **T**: Transpose of the array (for 2D arrays).

These attributes help you understand and manipulate arrays efficiently.

In [1]:
import numpy as np

Numpy Shape attribute gives us the total number of rows and columns in the array. The shape of the array is a tuple of two integers, where the first integer represents the number of rows and the second integer represents the number of columns.

In [2]:
arr= np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print(arr)

# checking the shape of the array
print(f"The array shape is: {arr.shape}")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
The array shape is: (2, 5)


In above code the array shape is (2, 5) which means it has 2 rows and 5 columns.

# Creating 3D Array

In [3]:
# Creating a 3D array using np.expand_dims (to add axes)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_3d = np.expand_dims(arr_2d, axis=0)  # Adds a new axis at position 0

print("Original 2D array:")
print(arr_2d)
print("\nExpanded to 3D array (shape {}):".format(arr_3d.shape))
print(arr_3d)

Original 2D array:
[[1 2 3]
 [4 5 6]]

Expanded to 3D array (shape (1, 2, 3)):
[[[1 2 3]
  [4 5 6]]]


# Using dtype() function

In [4]:
arr= np.array([1, 2, 3, 4, 5])
# Using dtype() function
print(f"The data type of the array elements is: {arr.dtype}")

The data type of the array elements is: int64


# Using Size() Function

In [5]:
arr.size

5

# Using nimdim() function

In [6]:
arr=np.array([1, 2, 3, 4, 5])
# This will give 1 bcz the array is 1D
print(f"The number of dimensions in the array is: {arr.ndim}")

The number of dimensions in the array is: 1


In [7]:
# len of the array
print(f"The length of the array is: {len(arr)}")

The length of the array is: 5


In [8]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(matrix[0, 1])  # Element at row 0, column 1 → 2
print(matrix[:, 2])  # All rows, column 2 → [3 6 9]


2
[3 6 9]


# Createing an Indentity Matrix

In [9]:
#using np.eye() function to create an identity matrix
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [10]:
type(arr)

numpy.ndarray