# Numpy Introduction



NumPy stands for Numerical Python.It is a powerful library for working with arrays and performing numerical computations efficiently.Unlike Python lists, NumPy arrays are faster and use less memory.


# Importing Numpy

In [1]:
import numpy as np

## Array
An array is a data structure that stores a collection of items (elements) of the same type in a single, contiguous block of memory. In NumPy, arrays are called ndarrays and can be multi-dimensional (e.g., 1D, 2D, 3D). Arrays allow efficient storage, access, and manipulation of numerical data, making them ideal for scientific and mathematical computations.

# Creating The Arrays:
There are multiple ways to create arrays in Numpy. Here are a few examples:
1. Using the `numpy.array()` function to create an array from a Python list or tuple
2. Using the `numpy.zeros()` function to create an array filled with zeros
3. Using the `numpy.ones()` function to create an array filled with ones
4. Using `np.arange()` to create an array with a specified range of values

## Creating Numpy Array From Python List

In [2]:
# python list

my_list = [1, 2, 3, 4, 5]
# converting python list to numpy array
arr=np.array(my_list)

print(arr)

[1 2 3 4 5]


## Creating The Array Using np.arange

In [3]:
# This will create a numpy array with elements from 0 to 5
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


## Creating Array with np.zeros()

In [4]:
# Creating an array filled with zeros
np.zeros(2)


array([0., 0.])

## Creating Array with np.ones()

In [5]:
np.ones(2)

array([1., 1.])

> Above are the Examples To create a 1D array. Now we will see how to create a 2D array

# Creating a 2D array

In [6]:
arr= np.array([0, 1, 2, 3, 4])
arr2=arr[np.newaxis,:]

print(arr2)

[[0 1 2 3 4]]


In [7]:
# create a 1d array with random values
arr = np.random.rand(5)
print("1D array with random values:")
print(arr)

1D array with random values:
[0.72529884 0.33143661 0.09811894 0.29073392 0.46655394]


In [8]:
full= np.full((2, 2), 7)
print("Array filled with 7s:")
print(full)

Array filled with 7s:
[[7 7]
 [7 7]]


# Using Empty Function

The function empty creates an array whose initial content is random and depends on the state of the memory. The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!

In [9]:
# Creating an empty array of 2x3
empty=np.empty((2,3))
print(empty)


[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [2.11394409e-307 2.67020135e-306 2.42092166e-322]]
